export const CONTACT = {
  name: 'Mail Boxes Etc. Colón',
  shortName: 'MBE Colón',
  address: 'Plaza Millenium Local F007, Colón, Panamá',
  phone: '474-5548',
  phoneHref: 'tel:+5074745548',
  whatsapp: '6949-5100',
  whatsappHref: 'https://wa.me/50769495100',
  email: 'mbecolon@gmail.com',
  emailHref: 'mailto:mbecolon@gmail.com',
  hours: {
    weekdays: 'Lunes a Viernes: 8:00 AM – 5:00 PM',
    saturday: 'Sábado: 9:00 AM – 1:00 PM',
    sunday: 'Domingo: Cerrado',
  },
  mapsEmbed: 'https://www.openstreetmap.org/export/embed.html?bbox=-79.9028769%2C9.3350748%2C-79.8828769%2C9.3550748&layer=mapnik&marker=9.3450748%2C-79.8928769',
  mapsLink: 'https://www.google.com/maps/place/Plaza+Millennium/@9.3450748,-79.8928769,17z/data=!3m1!4b1!4m6!3m5!1s0x8fab6da330fc828b:0x2a0506e0dd55d71a!8m2!3d9.3450748!4d-79.8928769',
}

export const SERVICES = [
  {
    id: 'envios-internacionales',
    icon: '✈️',
    title: 'Envíos Internacionales',
    description: 'Enviamos tus paquetes a todo el mundo desde Colón, Panamá con DHL, FedEx y UPS.',
    href: '/servicios/envios-internacionales',
  },
  {
    id: 'compras-internet',
    icon: '🛒',
    title: 'Compras por Internet',
    description: 'Compra en Amazon, eBay, Shein y recíbelo en Colón con tu casillero Miami.',
    href: '/servicios/compras-internet',
  },
  {
    id: 'carga-maritima',
    icon: '🚢',
    title: 'Carga Marítima',
    description: 'Carga marítima Miami–Panamá y China–Panamá al mejor precio para tu empresa.',
    href: '/servicios/carga-maritima',
  },
  {
    id: 'impresion',
    icon: '🖨️',
    title: 'Impresión Profesional',
    description: 'Tarjetas, brochures, banners y fotocopias con calidad profesional en Colón.',
    href: '/servicios/impresion',
  },
  {
    id: 'casillero',
    icon: '📬',
    title: 'Casillero Miami',
    description: 'Tu dirección en Miami para recibir compras de tiendas de USA y entregarlas en Colón.',
    href: '/servicios/casillero',
  },
  {
    id: 'bordados',
    icon: '🧵',
    title: 'Bordados Personalizados',
    description: 'Uniformes, hoodies, gorras y polos con tu logo bordado para empresas en Panamá.',
    href: '/servicios/bordados',
  },
  {
    id: 'sellos',
    icon: '🔖',
    title: 'Sellos Automáticos',
    description: 'Sellos automáticos personalizados para empresas y profesionales en Colón, Panamá.',
    href: '/servicios/sellos',
  },
]

export const WHY_US = [
  {
    icon: '📍',
    title: 'Ubicación Estratégica en Colón',
    description: 'En el corazón comercial de Colón, Plaza Millenium — fácil acceso para toda la provincia de Colón.',
    color: 'mbe-red',
  },
  {
    icon: '⚡',
    title: 'Eficiencia Total',
    description: 'Operamos con DHL, FedEx y UPS para garantizar los mejores tiempos de entrega en Panamá.',
    color: 'mbe-blue',
  },
  {
    icon: '🔒',
    title: 'Seguridad Garantizada',
    description: 'Embalaje profesional y seguro de carga incluido en todos tus envíos internacionales.',
    color: 'mbe-red',
  },
  {
    icon: '🏆',
    title: '18+ Años de Experiencia',
    description: 'Red de 34 centros MBE en Panamá. La franquicia de logística y envíos más confiable del país.',
    color: 'mbe-blue',
  },
]

export const HERO_SLIDES = [
  {
    id: 1,
    eyebrow: '📦 Mail Boxes Etc. — Plaza Millenium, Colón, Panamá',
    title: 'Envíos internacionales\ndesde Colón, Panamá.',
    description: 'Enviamos con DHL, FedEx y UPS desde Colón, Panamá. Tracking en tiempo real incluido.',
    cta: { text: 'Ver tarifas', href: '/servicios/envios-internacionales' },
    ctaSecondary: { text: 'Contáctanos', href: '#contacto' },
    bgClass: 'bg-mbe-dark',
  },
  {
    id: 2,
    eyebrow: 'Casillero Miami — Compra en USA desde Colón',
    title: '¡Recibe tus compras\nen 24-48 horas!',
    description: 'Amazon, eBay, Shein y más — con tu casillero Miami MBE, directo a Colón, Panamá.',
    cta: { text: 'Abre tu casillero gratis', href: '/servicios/casillero' },
    ctaSecondary: { text: 'Cómo funciona', href: '/servicios/compras-internet' },
    bgClass: 'bg-mbe-red',
  },
  {
    id: 3,
    eyebrow: 'Impresión profesional en Colón',
    title: 'Tarjetas, brochures\ny banners de calidad.',
    description: 'Impresión profesional para tu negocio en Colón, Panamá. Entrega el mismo día.',
    cta: { text: 'Solicitar cotización', href: '#contacto' },
    ctaSecondary: { text: 'Ver servicios', href: '/servicios/impresion' },
    bgClass: 'bg-mbe-gray',
  },
  {
    id: 4,
    eyebrow: 'Bordados personalizados en Panamá',
    title: 'Tu logo en uniformes,\nhoodies y gorras.',
    description: 'Bordados de alta calidad para uniformes empresariales y equipos en Colón y Panamá.',
    cta: { text: 'Ver bordados', href: '/servicios/bordados' },
    ctaSecondary: { text: 'Contáctanos', href: '#contacto' },
    bgClass: 'bg-mbe-dark',
  },
  {
    id: 5,
    eyebrow: 'Sellos automáticos personalizados — Colón, Panamá',
    title: 'Sellos personalizados\npara tu empresa.',
    description: 'Sellos automáticos para abogados, médicos y empresas en Colón. Entrega en 24-48 horas.',
    cta: { text: 'Pedir mi sello', href: '/servicios/sellos' },
    ctaSecondary: { text: 'Ver tipos', href: '/servicios/sellos' },
    bgClass: 'bg-mbe-blue',
  },
]
