export type Post = {
  categoria: string
  badge: string
  titulo: string
  desc: string
  href: string
  img: string
  imgAlt: string
  datePublished: string
  dateModified: string
}

export const POSTS: Post[] = [
  {
    categoria: 'Bordados',
    badge: 'bg-mbe-blue',
    titulo: 'Chaquetas y Camisas Bordadas para Empresas de Seguridad en Colón, Panamá',
    desc: 'Bordados Colón para empresas de seguridad: chaquetas y camisas con logo bordado, alta durabilidad y entrega rápida en Plaza Millenium F007.',
    href: '/blog/chaquetas-bordadas-empresas-seguridad-colon',
    img: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Chaqueta bordada con logo para empresa de seguridad en Colón, Panamá',
    datePublished: '2026-09-18',
    dateModified: '2026-09-18',
  },
  {
    categoria: 'Envíos',
    badge: 'bg-mbe-red',
    titulo: 'Cómo enviar documentos urgentes desde Colón, Panamá al mundo',
    desc: 'Envíos internacionales Colón para documentos urgentes: cómo elegir entre DHL, FedEx y UPS y evitar retrasos en aduana.',
    href: '/blog/envio-documentos-urgentes-colon',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Envío de documentos urgentes internacionales desde Colón, Panamá',
    datePublished: '2026-09-11',
    dateModified: '2026-09-11',
  },
  {
    categoria: 'Impresión',
    badge: 'bg-mbe-blue',
    titulo: 'Impresión de etiquetas y stickers personalizados para tu negocio en Colón, Panamá',
    desc: 'Impresión Colón de etiquetas y stickers personalizados para productos, envíos y packaging. Entrega rápida en Plaza Millenium F007.',
    href: '/blog/etiquetas-stickers-personalizados-colon',
    img: 'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Impresión de etiquetas y stickers personalizados para negocios en Colón, Panamá',
    datePublished: '2026-09-11',
    dateModified: '2026-09-11',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-red',
    titulo: '¿Cuánto cuesta el casillero Miami y traer un paquete a Colón en 2026?',
    desc: 'Precios reales del casillero Miami desde $3.00/lb (aéreo) y $3.00/ft³ (marítimo), con ejemplos de costos y qué impuestos pagas al importar a Panamá.',
    href: '/blog/cuanto-cuesta-casillero-miami-envio-colon',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: '¿Cuánto cuesta el casillero Miami y el envío a Colón, Panamá? — MBE Colón',
    datePublished: '2026-08-20',
    dateModified: '2026-08-20',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-blue',
    titulo: '¿Cuánto tarda un envío de Miami a Colón, Panamá?',
    desc: 'Tiempos reales de tu casillero: aéreo express 24-72 horas, estándar 3-7 días y marítimo 7-15 días hábiles. Qué factores afectan la entrega.',
    href: '/blog/cuanto-tarda-envio-miami-colon',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Tiempo de entrega de un envío de Miami a Colón, Panamá — MBE Colón',
    datePublished: '2026-08-20',
    dateModified: '2026-08-20',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-blue',
    titulo: '¿Cuánto se paga de impuesto al comprar por internet en Panamá en 2026?',
    desc: 'Qué impuestos pagas al importar con tu casillero: arancel por categoría, ITBMS del 7% y cómo MBE Colón gestiona tu trámite aduanal sin complicaciones.',
    href: '/blog/cuanto-se-paga-impuesto-comprar-internet-panama',
    img: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Impuestos aduanales al comprar por internet en Panamá — MBE Colón',
    datePublished: '2026-08-20',
    dateModified: '2026-08-20',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-red',
    titulo: 'Cómo comprar por internet desde Colón, Panamá en 2026: guía completa',
    desc: 'Guía paso a paso para comprar en Amazon, Shein y eBay y recibir tus paquetes en Colón con tu casillero Miami. Tarifas, tiempos y tips.',
    href: '/blog/como-comprar-por-internet-desde-colon-panama',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Cómo comprar por internet desde Colón, Panamá con casillero Miami MBE',
    datePublished: '2026-08-20',
    dateModified: '2026-08-20',
  },
  {
    categoria: 'Sellos',
    badge: 'bg-mbe-red',
    titulo: 'Sellos para notarías y bufetes de abogados en Colón, Panamá',
    desc: 'Sellos automáticos para notarías y bufetes de abogados en Colón, Panamá: sello de idóneo, notarial y de constancia. Entrega en 24-48h.',
    href: '/blog/sellos-notarias-bufetes-abogados-colon',
    img: 'https://images.unsplash.com/photo-1612178991541-b48cc8e92a4d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Sello automático para notaría y bufete de abogados en Colón, Panamá',
    datePublished: '2026-08-14',
    dateModified: '2026-08-14',
  },
  {
    categoria: 'Bordados',
    badge: 'bg-mbe-blue',
    titulo: 'Delantales y Chaquetas Bordadas para Restaurantes y Hoteles en Colón, Panamá',
    desc: 'Bordamos delantales, chaquetas y uniformes para restaurantes y hoteles en Colón, Panamá. Entrega rápida en Plaza Millenium F007.',
    href: '/blog/bordados-delantales-restaurantes-hoteles-colon',
    img: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Delantal bordado con logo para restaurante en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Envíos',
    badge: 'bg-mbe-blue',
    titulo: 'Seguro para tus Envíos Internacionales: Protege tus Paquetes desde Colón, Panamá',
    desc: 'Cómo asegurar tu paquete internacional desde Colón, Panamá. Protege tus envíos con DHL, FedEx y UPS y evita pérdidas en tu courier.',
    href: '/blog/seguro-envios-internacionales-colon',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Paquete asegurado listo para envío internacional desde Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-09-24',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-blue',
    titulo: 'Cómo Comprar Electrónicos y Gadgets en USA con tu Casillero Miami desde Colón',
    desc: 'Compra laptops, celulares y gadgets en Amazon, Best Buy y B&H con tu casillero Miami. Recíbelos en Colón, Panamá en 24-48h.',
    href: '/blog/casillero-miami-electronicos-gadgets-colon',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Compra de laptops y gadgets electrónicos con casillero Miami MBE Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Impresión',
    badge: 'bg-mbe-blue',
    titulo: 'Impresión de Banners y Afiches Publicitarios en Colón, Panamá',
    desc: 'Impresión de banners publicitarios en Colón Panamá: vinil, pendones roll-up y afiches. Entrega en 24-48h en Plaza Millenium F007.',
    href: '/blog/impresion-banners-afiches-publicitarios-colon',
    img: 'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Impresión de banner publicitario en vinil para negocio en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-09-24',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-blue',
    titulo: 'Consolidación de carga para PYMEs en Colón: reduce tus costos de importación',
    desc: 'Cómo la consolidación de carga reduce costos de importación para PYMEs en la Zona Libre de Colón, Panamá.',
    href: '/blog/consolidacion-carga-pymes-colon',
    img: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Consolidación de carga marítima para PYMEs en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Sellos',
    badge: 'bg-mbe-red',
    titulo: 'Kit de identidad corporativa para nuevas empresas en Colón, Panamá',
    desc: 'Sellos automáticos, carnets PVC y papelería membretada para tu nueva empresa en Colón. Todo en un solo lugar, Plaza Millenium F007.',
    href: '/blog/kit-identidad-corporativa-empresas-colon',
    img: 'https://images.unsplash.com/photo-1612178991541-b48cc8e92a4d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Sello automático y carnet corporativo para nueva empresa en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Bordados',
    badge: 'bg-mbe-blue',
    titulo: 'Hoodies bordados con logo para empresas en Colón, Panamá',
    desc: 'Bordados personalizados para empresas en Colón Panamá: hoodies con logo de alta calidad, entrega rápida en Plaza Millenium F007.',
    href: '/blog/hoodies-bordados-empresas-colon',
    img: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Hoodie bordado con logo de empresa en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Envíos',
    badge: 'bg-mbe-red',
    titulo: '¿Cuánto cuesta enviar un paquete internacional desde Colón, Panamá?',
    desc: 'Guía de precios para tus envíos internacionales Colón: qué determina el costo y cómo comparar DHL, FedEx y UPS.',
    href: '/blog/costo-envios-internacionales-desde-colon',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Cajas de paquetes listas para envío internacional desde Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-blue',
    titulo: 'Cómo comprar en Shein y eBay desde Colón con tu casillero Miami',
    desc: 'Recibe tus paquetes de Shein y eBay en Colón, Panamá con el casillero Miami de MBE. Rápido, seguro y sin costo de inscripción.',
    href: '/blog/casillero-miami-shein-ebay-colon',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Compras online de Shein y eBay con casillero Miami MBE Colón',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Impresión',
    badge: 'bg-mbe-blue',
    titulo: 'Tarjetas de presentación y embalaje profesional para tu empresa en Colón, Panamá',
    desc: 'Impresión de tarjetas de presentación y embalaje profesional para empresas en Colón, Panamá. Entrega en 24-48h en Plaza Millenium F007.',
    href: '/blog/impresion-tarjetas-embalaje-profesional-colon',
    img: 'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Impresión de tarjetas de presentación y embalaje profesional para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-red',
    titulo: 'Carga marítima Miami-Panamá para empresas en Colón',
    desc: 'Servicio de carga marítima Miami-Panamá para empresas en Colón, Panamá. Logística para PYMEs y la Zona Libre de Colón.',
    href: '/blog/carga-maritima-miami-panama-empresas-colon',
    img: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Almacén de carga marítima Miami-Panamá para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Sellos',
    badge: 'bg-mbe-red',
    titulo: 'Carnets PVC personalizados para empresas en Colón, Panamá',
    desc: 'Carnets de identificación con logo, foto y código de barras para empresas en Colón. Diseño a color, entrega en 24-48h. Plaza Millenium F007.',
    href: '/blog/carnets-pvc-personalizados-empresas-colon',
    img: 'https://images.unsplash.com/photo-1612178991541-b48cc8e92a4d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Carnets PVC personalizados para identificación de empleados en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Bordados',
    badge: 'bg-mbe-blue',
    titulo: 'Gorras y polos bordados con logo para empresas en Colón, Panamá',
    desc: 'Bordados de calidad en Colón: gorras y polos con logo para empresas y PYMEs, desde 1 unidad. Plaza Millenium F007.',
    href: '/blog/bordados-gorras-polos-empresas-colon',
    img: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Gorras y polos bordados con logo para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Envíos',
    badge: 'bg-mbe-blue',
    titulo: 'Envíos internacionales desde Colón: ¿DHL, FedEx o UPS? Guía para elegir tu courier',
    desc: 'Compara DHL, FedEx y UPS para tus envíos internacionales desde Colón, Panamá según destino, peso y presupuesto.',
    href: '/blog/envios-internacionales-dhl-fedex-ups-colon',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Cajas de paquetes para envíos internacionales desde Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-red',
    titulo: 'Logística en Colón para PYMEs y operadores de la Zona Libre: todo en un solo lugar',
    desc: 'Servicios de logística para empresas en Colón, Panamá. Carga marítima Miami-Panamá, DHL, FedEx y UPS con entrega en 24-48h a la Zona Libre de Colón.',
    href: '/blog/logistica-pymes-zona-libre-colon',
    img: 'https://images.unsplash.com/photo-1566492031773-4f4e44671857?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Almacén logístico para empresas y PYMEs en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Impresión',
    badge: 'bg-mbe-blue',
    titulo: 'Impresión profesional en Colón: planos arquitectónicos, brochures y banners para tu empresa',
    desc: 'Imprimimos planos en gran formato, brochures corporativos y banners para empresas en Colón, Panamá. Calidad profesional y entrega rápida.',
    href: '/blog/impresion-planos-brochures-colon',
    img: 'https://images.unsplash.com/photo-1586769852836-bc069f19e1b6?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Impresión profesional de planos y brochures para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Sellos',
    badge: 'bg-mbe-red',
    titulo: '¿Dónde hacer sellos automáticos personalizados en Colón, Panamá?',
    desc: 'Sellos automáticos para abogados, médicos y empresas en Colón. Modelos Trodat y Colop, entrega en 24-48h. Plaza Millenium F007.',
    href: '/blog/sellos-automaticos-personalizados-colon',
    img: 'https://images.unsplash.com/photo-1612178991541-b48cc8e92a4d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Sello automático personalizado con tinta para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Bordados',
    badge: 'bg-mbe-blue',
    titulo: '¿Dónde bordar uniformes con tu logo en Colón, Panamá? Guía para empresas',
    desc: 'Bordados personalizados en uniformes, hoodies y gorras para empresas en Colón. Desde 1 unidad, alta durabilidad garantizada.',
    href: '/blog/bordados-personalizados-uniformes-colon',
    img: 'https://images.unsplash.com/photo-1516762689617-e1cffcef479d?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Bordados personalizados en uniformes y gorras para empresas en Colón, Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Envíos',
    badge: 'bg-mbe-red',
    titulo: '¿Cómo empacar correctamente tu paquete para envíos internacionales?',
    desc: 'Aprende las mejores técnicas de embalaje para proteger tus envíos con DHL, FedEx y UPS desde Colón, Panamá.',
    href: '/blog/como-empacar-paquetes',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Cajas de paquetes listos para envío internacional',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-blue',
    titulo: 'Guía completa para comprar en Amazon y recibir en Colón',
    desc: 'Paso a paso: cómo usar tu casillero Miami MBE para traer tus compras de USA sin complicaciones.',
    href: '/blog/guia-compras-amazon-colon',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Compras online en Amazon con casillero Miami MBE Colón',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-red',
    titulo: 'Cómo traer repuestos de auto desde USA a Panamá',
    desc: 'Guía paso a paso para comprar piezas de carro en USA y recibirlas rápido y seguro en Colón, Panamá.',
    href: '/blog/traer-repuestos-auto-usa-panama',
    img: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Mecánico instalando repuestos de auto importados desde USA a Panamá',
    datePublished: '2026-08-13',
    dateModified: '2026-08-13',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-blue',
    titulo: 'Trámites de aduana en Panamá para compras online y casillero',
    desc: 'Documentos, proceso ante la ANA, aranceles e ITBMS y errores comunes al importar. MBE Colón gestiona tu trámite aduanal de principio a fin.',
    href: '/blog/tramites-aduana-panama',
    img: 'https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Trámites de aduana en Panamá para compras online con casillero',
    datePublished: '2025-03-05',
    dateModified: '2025-03-05',
  },
  {
    categoria: 'Logística',
    badge: 'bg-mbe-red',
    titulo: 'Qué son los incoterms y para qué sirven en tus importaciones',
    desc: 'Qué es cada incoterm (EXW, FOB, CIF, DDP), quién paga el flete y quién asume la aduana, y cómo elegir el correcto para tu envío desde USA o China.',
    href: '/blog/que-son-los-incoterms-y-para-que-sirven',
    img: 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Incoterms explicados para importaciones y envíos internacionales',
    datePublished: '2023-09-04',
    dateModified: '2023-09-04',
  },
  {
    categoria: 'Casillero',
    badge: 'bg-mbe-blue',
    titulo: 'Las fechas más importantes para comprar por internet en el año',
    desc: 'Calendario de ofertas y fechas clave (Prime Day, Black Friday, Cyber Monday, Navidad) para comprar desde USA y ahorrar con tu casillero Miami.',
    href: '/blog/las-fechas-mas-importantes-para-comprar-por-internet',
    img: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=600&h=280&fit=crop&q=80',
    imgAlt: 'Calendario de ofertas para comprar por internet desde Panamá',
    datePublished: '2023-09-01',
    dateModified: '2023-09-01',
  },
]
